### ISSUE TITLE
Missing wireguard dependency

### ISSUE THREAD

**Issue by arclabs561** [danderson/tailscale-aur#1]
I was following the instructions for installing tailscale here: https://tailscale.com/kb/1036/install-arch. Watching journctl logs I saw the errors:
```
Feb 17 11:42:37 kabuto relaynode[31062]: 2020/02/17 11:42:37 CreateTUN: no such device
Feb 17 11:42:37 kabuto relaynode[31062]: 2020/02/17 11:42:37 Error starting wireguard engine: no such device
Feb 17 11:42:37 kabuto systemd[1]: tailscale-relay.service: Main process exited, code=exited, status=1/FAILURE
```

Then I realized that I had didn't have wireguard installed. So I installed `wireguard-arch` and `wireguard-tools`, and it works now. Should we add those as dependencies, or is it intentionally left out because there are several ways to install it

**Comment by danderson** [comment]
Tailscale should not depend on the kernel wireguard implementation, currently we only use the userspace Go implementation.

Based on the error, I suspect you upgraded your kernel, and so the `tuntap` module failed to load (because it was for a newer kernel version). Can you try removing the wireguard packages and rebooting to resync your kernel with your installed modules?

**Comment by arclabs561** [comment]
Oh interesting. Yes removing those packages, then rebooting, shows no journalctl errors. Thanks
